name: Avoma Frontend Version Bump
run-name: Bump version by [bypass-rule-test[bot]]

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  version-bump:
    if: ${{ github.actor != 'bypass-rule-test[bot]' && github.event_name != 'push' || github.event.pusher.name != 'bypass-rule-test[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      actions: 'read'
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Publish New Version
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git checkout main && yarn config set version-git-message "bumped version to v%s" && yarn version --new-version minor && git push
