name: Publish Packages
on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      packages: 'write'
      actions: 'read'
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # pulls all history and tags for Lerna to detect which packages changed
          token: ${{ steps.app-token.outputs.token }}
      # lerna can only add a commit if git user infos are set
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      # - name: Install Dependencies
      #   run: npm ci
      #   shell: bash

      - name: publish
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "yarn version --new-version minor && git checkout main && git add . && git commit -m 'Bumped minor version' && git push"
