name: Sample Workflow

on:
  workflow_run:
    workflows: [Avoma Frontend Version Bump]
    types:
      - completed

jobs:
  sample-workflow-testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
