name: Sample Workflow

on:
  workflow_run:
    workflows: [Avoma Frontend Version Bump]
    types:
      - completed
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
