name: Deployment

on:
  workflow_run:
    workflows: [Avoma Frontend Version Bump]
    types:
      - completed

jobs:
  sample-workflow-testing:
    if: ${{ github.actor != 'bypass-rule-test[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
